steps:
  - name: "node:current-slim"
    entrypoint: npm
    id: Install Dependencies
    args:
      - ci
  - name: gcr.io/cloud-builders/docker
    id: Build Docker image
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
      - .
  - name: gcr.io/cloud-builders/docker
    id: Push Docker image
    args:
      - push
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
  - name: gcr.io/cloud-builders/gcloud
    id: Deploy to Cloud Run
    args:
      - run
      - deploy
      - $REPO_NAME-$BRANCH_NAME
      - "--image"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
      - "--region"
      - europe-north1
      - "--platform"
      - managed
      - "--max-instances"
      - "2"
